<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="openai_api_key"><?php echo _t('ext.field.openai_api_key'); ?></label>
		<div class="group-controls">
			<input type="text" name="openai_api_key" id="openai_api_key" value="<?php echo FreshRSS_Context::$system_conf->openai_api_key ?? ''; ?>">
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="max_tokens"><?php echo _t('ext.field.max_tokens'); ?></label>
		<div class="group-controls">
			<input type="range" name="max_tokens" id="max_tokens" min="7" max="4096" value="<?php echo FreshRSS_Context::$system_conf->max_tokens ?? 2048; ?>">
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="temperature"><?php echo _t('ext.field.temperature'); ?></label>
		<div class="group-controls">
			<input type="range" name="temperature" id="temperature" min="0" max="2" step="0.1" value="<?php echo FreshRSS_Context::$system_conf->temperature ?? 1.0; ?>">
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="limit"><?php echo _t('ext.field.limit'); ?></label>
		<div class="group-controls">
			<input type="number" name="limit" id="limit" value="<?php echo FreshRSS_Context::$system_conf->limit ?? 30; ?>">
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="prompt"><?php echo _t('ext.field.prompt'); ?></label>
		<div class="group-controls">
			<textarea id="prompt" name="prompt" rows="4" cols="50"><?php echo FreshRSS_Context::$system_conf->prompt ?? 'Summarize this as you are news editor, you should merge the similar topic.'; ?></textarea>
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="model"><?php echo _t('ext.field.model'); ?></label>
		<div class="group-controls">
			<select name="model" id="model">
				<option value="<?php echo htmlentities(FreshRSS_Context::$system_conf->model ?? 'text-davinci-003'); ?>" selected="selected"><?php echo htmlentities(FreshRSS_Context::$system_conf->model ?? 'text-davinci-003'); ?></option>
				<option value="-">-</option>
				<option value="babbage">babbage</option>
				<option value="davinci">davinci</option>
				<option value="text-davinci-001">text-davinci-001</option>
				<option value="ada">ada</option>
				<option value="text-curie-001">text-curie-001</option>
				<option value="text-davinci-003">text-davinci-003</option>
				<option value="text-ada-001">text-ada-001</option>
				<option value="curie-instruct-beta">curie-instruct-beta</option>
				<option value="davinci-instruct-beta">davinci-instruct-beta</option>
				<option value="text-babbage-001">text-babbage-001</option>
				<option value="curie">curie</option>
				<option value="text-davinci-002">text-davinci-002</option>
			</select>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>