<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="openai_api_key"><a href="https://platform.openai.com/account/api-keys" target="_blank"><?php echo _t('ext.field.openai_api_key') . " (?)"; ?></a></label>
		<div class="group-controls">
			<input type="text" name="openai_api_key" id="openai_api_key" value="<?php echo FreshRSS_Context::$system_conf->openai_api_key ?? ''; ?>">
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="max_tokens"><a href="https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens" target="_blank"><?php echo _t('ext.field.max_tokens') . " (?)"; ?></a></label>
		<div class="group-controls">
			<input type="range" name="max_tokens" id="max_tokens" min="7" max="4096" value="<?php echo FreshRSS_Context::$system_conf->max_tokens ?? 2048; ?>">
			<output for="max_tokens"><?php echo FreshRSS_Context::$system_conf->max_tokens ?? 2048; ?></output>
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="temperature"><a href="https://platform.openai.com/docs/api-reference/completions/create#completions/create-temperature" target="_blank" ><?php echo _t('ext.field.temperature') . " (?)"; ?></a></label>
		<div class="group-controls">
			<input type="range" name="temperature" id="temperature" min="0" max="2" step="0.1" value="<?php echo FreshRSS_Context::$system_conf->temperature ?? 1.0; ?>">
			<output for="temperature"><?php echo FreshRSS_Context::$system_conf->temperature ?? 1.0; ?></output>
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="field"><?php echo _t('ext.field.field'); ?></label>
		<div class="group-controls">
			<select name="field" id="field">
				<option value="<?php echo htmlentities(FreshRSS_Context::$system_conf->field ?? 'content'); ?>" selected="selected"><?php echo htmlentities(FreshRSS_Context::$system_conf->field ?? 'content'); ?></option>
				<option value="title">title</option>
				<option value="content">content</option>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="limit"><?php echo _t('ext.field.limit'); ?></label>
		<div class="group-controls">
			<input type="number" name="limit" id="limit" value="<?php echo FreshRSS_Context::$system_conf->limit ?? 30; ?>">
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="prompt"><a href="https://platform.openai.com/docs/api-reference/completions/create#completions/create-prompt" target="_blank" ><?php echo _t('ext.field.prompt') . " (?)"; ?></a></label>
		<div class="group-controls">
			<textarea id="prompt" name="prompt" rows="4" cols="50"><?php echo FreshRSS_Context::$system_conf->prompt ?? 'Summarize this as you are news editor, you should merge the similar topic.'; ?></textarea>
		</div>
	</div>
	<div class="form-group">
		<!-- make the input element to support input and select -->
		<label class="group-name" for="model"><a href="https://platform.openai.com/docs/api-reference/completions/create#completions/create-model" target="_blank"><?php echo _t('ext.field.model') . " (?)"; ?></a></label>
		<div class="group-controls">
			<select name="model" id="model">
				<option value="<?php echo htmlentities(FreshRSS_Context::$system_conf->model ?? 'gpt-3.5-turbo-16k'); ?>" selected="selected"><?php echo htmlentities(FreshRSS_Context::$system_conf->model ?? 'gpt-3.5-turbo-16k'); ?></option>
				<option value="-">-</option>
				<option value="gpt-4">gpt-4</option>
				<option value="gpt-4-0613">gpt-4-0613</option>
				<option value="gpt-4-32k">gpt-4-32k</option>
				<option value="gpt-4-32k-0613">gpt-4-32k-0613</option>
				<option value="gpt-3.5-turbo">gpt-3.5-turbo</option>
				<option value="gpt-3.5-turbo-0613">gpt-3.5-turbo-0613</option>
				<option value="gpt-3.5-turbo-16k">gpt-3.5-turbo-16k</option>
				<option value="gpt-3.5-turbo-16k-0613">gpt-3.5-turbo-16k-0613</option>
			</select>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>