<div id="loader" class="loader">
	<div class="spinner"></div>
</div>
<div class="post content">
	<h1><?php echo _t('gen.layout.title'); ?></h1>
	<p id="summary_content"></p>
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="button" class="btn btn-important badge-button" id="set_read_btn" title="Mark the articles to be read">
				<?php echo _t('gen.action.set_read'); ?>
				<span id="read_badge" class="badge"></span>
			</button>
			<a class="btn" href="./"><?php echo _t('gen.action.back'); ?></a>
		</div>
	</div>
</div>